# Generated by Django 6.0.5 on 2026-05-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='baseprofile',
            new_name='core_basepr_role_0ecb77_idx',
            old_name='core_basepr_role_afa4dc_idx',
        ),
        migrations.RenameIndex(
            model_name='companypost',
            new_name='core_compan_post_ty_859f60_idx',
            old_name='core_compan_post_ty_1ee4f2_idx',
        ),
        migrations.RenameIndex(
            model_name='companypost',
            new_name='core_compan_created_f0c120_idx',
            old_name='core_compan_created_b0b823_idx',
        ),
        migrations.RenameIndex(
            model_name='refreshtoken',
            new_name='core_refres_user_id_75ec93_idx',
            old_name='core_refres_user_id_7ecf15_idx',
        ),
    ]
